name: ViewExtra_Mono
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - pytorch3d 
  - iopath
dependencies:
  - python=3.11
  - pytorch==2.2.0 
  - torchvision==0.17.0 
  - torchaudio==2.2.0 
  - pytorch-cuda=12.1
  - pytorch3d=0.7.7
  - iopath
  - pip:
      - diffusers==0.29.1
      - numpy==1.26.4
      - transformers==4.41.2
      - accelerate==0.31.0

