name: ViewExtra_Multi
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch==2.2.0 
  - torchvision==0.17.0 
  - torchaudio==2.2.0 
  - pytorch-cuda=12.1
  - pip:
      - git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e
      - diffusers==0.29.1
      - numpy==1.26.4
      - transformers==4.41.2
      - accelerate==0.31.0
      - viser==0.2.9
      - imageio[ffmpeg]
      - numpy==1.26.4
      - matplotlib==3.9.2
      - scikit-learn
      - tqdm
      - torchmetrics[image]
      - opencv-python
      - tyro
      - Pillow
      - tensorboard
      - gsplat==1.1.1


